create table users (
                       id int8 generated by default as identity,
                       username varchar(64),
                       password varchar(64),
                       primary key (id)
);

INSERT into users (username, password) values ('admin', '123');